### ISSUE TITLE
Why config.global_inventory is empty?

### ISSUE THREAD

**Issue by januradha** [janiko71/aws-inventory#11]
https://github.com/janiko71/aws-inventory/blob/aed0f80d4f2ac88c6addb46ccd60046c48e4106f/config.py#L73

since config.global_inventory list is empty so getting below error

Error :
Traceback (most recent call last):
  File "/var/task/call_aws_inventory.py", line 5, in get_aws_inventory
    inventory.call_inventory()
  File "/var/task/inventory.py", line 123, in call_inventory
    inventory[svc] = config.global_inventory[svc]
KeyError: 's3'

**Comment by janiko71** [comment]
Hi, thank you for your feedback. It seems that you don't use the script directly but from your own program. Could you tell me:

1. Is the output file OK? In the folder 'output' you should find a AWS_xxxxx.json file with the inventory.
1. How to you call the inventory in your python? My script is not a module, the variables I use in it may be out of the scope of your programm, see https://docs.python.org/3/reference/executionmodel.html.
