### ISSUE TITLE
Issue about region specal endpoint 

### ISSUE THREAD

**Issue by coffeedev2k** [janiko71/aws-inventory#56]
$ docker run --name zolotnik-015291475736 -v /tmp/aws-inventory/output:/usr/src/app/output -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_015291475736} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_015291475736} ${REGISTRY_OVH}/zolotnik:latest python ./inventory.py --services s3 ec2 rds dynamodb ecs cloudwatch route53 elb elbv2 ecr
----------------------------------------------------------------------------------------------------
Number of services   : 10
Services List        : ['s3', 'ec2', 'rds', 'dynamodb', 'ecs', 'cloudwatch', 'route53', 'elb', 'elbv2', 'ecr']
----------------------------------------------------------------------------------------------------
Exception in thread Thread-[20](https://gitlab.qoden.net/qoden/zolotnik/-/jobs/472781#L20):
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/src/app/res/awsthread.py", line 48, in run
    config.global_inventory[self.aws_service] = self.function_name(*self.arg)
  File "/usr/src/app/res/storage.py", line 114, in get_s3_inventory
    for objects in page_objects:
  File "/usr/local/lib/python3.8/site-packages/botocore/paginate.py", line [26](https://gitlab.qoden.net/qoden/zolotnik/-/jobs/472781#L26)9, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the ListObjectsV2 operation: The me-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.
Traceback (most recent call last):
  File "./inventory.py", line 573, in <module>
    inventory[svc] = config.global_inventory[svc]
KeyError: 's3'

**Comment by janiko71** [comment]
Hi, sorry for the delay. Is your issue still present? Do you have the AWS_Regions_List.json file?
